name: Deploy React App to Google Cloud Run

on:
  push:
    branches:
      - main  # Runs when code is pushed to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_AUTH_TOKEN }}

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and Push Docker Image
      run: |
        docker build -t us-central1-docker.pkg.dev/chrome-setup-445605-f8/my-repo/react-app:latest .
        docker push us-central1-docker.pkg.dev/chrome-setup-445605-f8/my-repo/react-app:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy react-app \
          --image=us-central1-docker.pkg.dev/chrome-setup-445605-f8/my-repo/react-app:latest \
          --platform=managed \
          --region=us-central1 \
          --allow-unauthenticated
